version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5442:5432"
    expose:
      - "5442"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: